# Generated by Django 5.1.5 on 2025-02-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_parent',
        ),
    ]
